### ISSUE TITLE
QA_Short-time spectrum analysis of_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#10]
Defect Description:
In the experiment page of the "Short-time spectrum analysis of speech", without clicking on the play button the record button is enabled where the record button should be disabled.

Actual Result :
In the experiment page of the "Short-time spectrum analysis of speech", without clicking on the play button the record button is enabled

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/peech-signal-processing-iiith/blob/master/test-cases/integration_test-cases/Short-time%20spectrum%20analysis%20of/Short-time%20spectrum%20analysis%20of_07_Experiment_p1.org

Attachment:
![short](https://cloud.githubusercontent.com/assets/14869397/14705353/b4b320ca-07d6-11e6-9061-aa3e090cf99c.png)

**Comment by BSravanthi** [comment]
Closing the issue as the issue is differed.
