### ISSUE TITLE
QA_Nature of speech signal_1.0_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#12]
Defect Description:
In the experiment page of the "Nature of speech signal", without clicking on the play button the record button is enabled where the record button should be disabled.
Actual Result :
In the experiment page of the "Nature of speech signal", without clicking on the play button the record button is enabled

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/peech-signal-processing-iiith/blob/master/test-cases/integration_test-cases/Nature%20of%20speech%20signal_1.0/Nature%20of%20speech%20signal_1.0_07_Experiment_p1.org

Attachment:
![nature](https://cloud.githubusercontent.com/assets/14869397/14705410/03442d1a-07d7-11e6-862d-6a7e9801a43d.png)

**Comment by sravanthimodepu** [comment]
This issue is differed.

**Comment by BSravanthi** [comment]
Closed the issue.
