### ISSUE TITLE
QA_Speech production mechanism_1.0_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#14]
Defect Description:
When we click on the experiment link of the "Speech production mechanism", it is redirecting to a blank screen instead it should redirect to the simulation page

Actual Result :
When we click on the experiment link of the "Speech production mechanism", it is redirecting to a blank screen

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/peech-signal-processing-iiith/blob/master/test-cases/integration_test-cases/Speech%20production%20mechanism_1.0/Speech%20production%20mechanism_1.0_07_Experiment_p1.org

Attachment:
![manual](https://cloud.githubusercontent.com/assets/14869397/14705745/ac582108-07d8-11e6-9a8c-e857f687e2a5.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed the issue.
