### ISSUE TITLE
Broken links in the Home page of Speech signal Processing Lab

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#17]
@sravanthimodepu  In the Home page of Speech Signal Processing Lab, few links are broken. When we click on the Logo link on the top left corner, the Home, Partners, Contact on the top right corner and in the Footer - FAQ links are broken . These links are leading to an error page where a massage is displaying "The requested URL /faq.html was not found on this server." Instead the above links should redirect to the concerned page.

**Comment by sravanthimodepu** [comment]
All the links are updated.

**Comment by BSravanthi** [comment]
Issue is closed.
