### ISSUE TITLE
navigation bar is not sticky!!

### ISSUE THREAD

**Issue by AkashV420** [virtual-labs/speech-signal-processing-iiith#184]
![speech1](https://user-images.githubusercontent.com/44038448/54492041-2c572800-48e9-11e9-9273-0052295e051a.png)

AFTER SCROLL DOWN..

![speech2](https://user-images.githubusercontent.com/44038448/54492047-37aa5380-48e9-11e9-89ba-d4da04a94d21.png)

**Comment by killerdns** [comment]
Fixed issue....
Commit id : 1eb8398.
