### ISSUE TITLE
QA_Defect_Manual speech signal-to-symbol transformatio_03

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#2]
Defect Description:
when we click on the reffered links in the reference page of "Manual speech signal-to-symbol transformation" experiment it is not redirecting to the referred link where it should redirect to the reffered link.
.

Actual Result :
when we click on the reffered links in the reference page of "Manual speech signal-to-symbol transformation" experiment it is not redirecting to the referred link

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Severity : S2

**Comment by sravanthimodepu** [comment]
Link is updated. Issue is fixed now.

**Comment by BSravanthi** [comment]
@sravanthimodepu As there is no Reference page is included in the Speech Signal Processing Lab, I could not close the issue. Please check the issue and revert back.

**Comment by BSravanthi** [comment]
Issue is closed..
