### ISSUE TITLE
Broken link in the Manual speech signal-to-symbol transformation Experiment page of Speech signal Processing Lab

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#20]
@sravanthimodepu  In the Manual speech signal-to-symbol transformation Experiment page of Speech Signal Processing Lab, the FAQ link under the footer section is broken. The link is leading to an error page where a massage is displaying "The requested URL /faq.html was not found on this server." Instead the above link should redirect to the concerned page.

**Comment by sravanthimodepu** [comment]
All the links in the lab are updated.

**Comment by BSravanthi** [comment]
Issue is closed as the issue is resolved.
