### ISSUE TITLE
Broken link for FAQ in all the pages of Speech signal Processing Lab

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#21]
@sravanthimodepu  The FAQ link under the footer section is broken in all the pages of the Speech signal Processing Lab. The link is leading to an error page where a massage is displaying "The requested URL /faq.html was not found on this server." Instead the above link should redirect to the concerned page.

**Comment by sravanthimodepu** [comment]
The FAQ link under the footer section is updated now with faq.html file.

**Comment by BSravanthi** [comment]
Issue is closed as all the links are working fine.
