### ISSUE TITLE
Broken link for FAQ in the Feedback page of Speech signal Processing Lab

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#25]
@sravanthimodepu The FAQ link under the footer section is broken in the Feedback page of the Speech signal Processing Lab. The link is leading to an error page where a massage is displaying "The requested URL /faq.html was not found on this server." Instead the above link should redirect to the concerned page.

**Comment by sravanthimodepu** [comment]
FAQ link under footer section is working now, I have created faq.html file and updated  in the lab.

**Comment by BSravanthi** [comment]
Issue is fixed, hence closing the issue
