### ISSUE TITLE
QA_speech-signal-processing-introduction_Target-Audiance_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#26]
Defect Description:
In the Target  Audience sub-section of the introduction section of Speech Signal Processing Lab, Found spelling mistakes. In the Sub section title itself the **Audience** spelling is given as **Audiance**. Hence this will gives a spelling error in every unit of the lab. 

Actual Result:
In the Target  Audience sub-section of the introduction section of Speech Signal Processing Lab, Found spelling mistakes. In the Sub section title itself the **Audience** spelling is given as **Audiance**. Hence this will gives a spelling error in every unit of the lab. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i01](https://cloud.githubusercontent.com/assets/13479177/26518509/c18c6b5a-42cf-11e7-8248-9c86726f86e2.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistake. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #26
