### ISSUE TITLE
QA_speech-signal-processing-introduction_Pre-requisites_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#27]
Defect Description:
In the Pre requisites sub-section of the introduction section of Speech Signal Processing Lab, Found spelling mistakes. In the Sub section title itself the **Pre requisites** spelling is given as  **Pre-requistes**.  In bread crump also spelled wrongly. Hence this will gives a spelling error in every test step of the lab.

Actual Result:
In the Pre requisites sub-section of the introduction section of Speech Signal Processing Lab, Found spelling mistakes. In the Sub section title itself the **Pre requisites** spelling is given as  **Pre-requistes**.  In bread crump also spelled wrongly. Hence this will gives a spelling error in every test step of the lab.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i02](https://cloud.githubusercontent.com/assets/13479177/26518655/39ff97ae-42d2-11e7-9907-ad94c43f6c78.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #27
