### ISSUE TITLE
QA_speech-signal-processing_Manual speech signal-to-symbol transformation_procedure_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#28]
Defect Description:
In the Procedure page of the **Manual speech signal-to-symbol transformation** experiment in Speech Signal Processing Lab, Found spelling mistakes. 

Actual Result:
In the Procedure page of the **Manual speech signal-to-symbol transformation** experiment in Speech Signal Processing Lab, Found spelling mistakes. 
**occurances** spelling is wrong.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments: 
![qa_oe_ssp_i03](https://cloud.githubusercontent.com/assets/13479177/26518693/0f87c5f4-42d3-11e7-964c-dca89f761876.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #28
