### ISSUE TITLE
QA_speech-signal-processing_Nature of speech signal_Observations_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#32]
Defect Description:
In the Observations page of the Nature of speech signal experiment in Speech Signal Processing Lab, Found spelling mistakes.

Actual Result:
In the Observations page of the Nature of speech signal experiment in Speech Signal Processing Lab, Found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i07](https://cloud.githubusercontent.com/assets/13479177/26519526/4b4c151a-42e0-11e7-85f5-d174ee2bdb85.png)

**Comment by sravanthimodepu** [comment]
NO spelling mistakes were found.Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #32
