### ISSUE TITLE
QA_speech-signal-processing_Basics of DSP_Tutorial_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#33]
Defect Description:
In the Tutorial page of the Basics of DSP experiment in Speech Signal Processing Lab, Found spelling mistakes.

Actual Result:
In the Tutorial page of the Basics of DSP experiment in Speech Signal Processing Lab, Found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i08](https://cloud.githubusercontent.com/assets/13479177/26519574/3e506ec8-42e1-11e7-9ec6-30bcb0cff5e2.png)

**Comment by sravanthimodepu** [comment]
Mistakes found in the page are special characters not spelling mistakes. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #33
