### ISSUE TITLE
QA_speech-signal-processing_Basics of DSP_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#34]
Defect Description:
In the experiment page of the Basics of DSP experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Actual Result:
In the experiment page of the Basics of DSP experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i09](https://cloud.githubusercontent.com/assets/13479177/26519640/89e71af2-42e2-11e7-891a-0e92f1c50254.png)

**Comment by sravanthimodepu** [comment]
Differing the issue, as the simulation is enabled on the small screen.
![screenshot from 2017-06-27 12 15 56](https://user-images.githubusercontent.com/11156924/27574117-a74a8e68-5b32-11e7-9542-f1f15e2e990e.png)
