### ISSUE TITLE
QA_speech-signal-processing_Short-time spectrum analysis of speech_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#35]
Defect Description:
In the experiment page of the Short-time spectrum analysis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Actual Result:
In the experiment page of the Short-time spectrum analysis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i10](https://cloud.githubusercontent.com/assets/13479177/26519785/f9b63fc4-42e3-11e7-8c7b-aa1c45436c97.png)

**Comment by sravanthimodepu** [comment]
Simulation was enabled in the small screen, hence differing the issue.
![ssp](https://user-images.githubusercontent.com/11156924/27851093-49c248d6-6176-11e7-8f7d-2ae3cd57a1db.png)
