### ISSUE TITLE
QA_speech-signal-processing_Spectrographic analysis of speech_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#36]
Defect Description:
In the experiment page of the Spectrographic analysis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Actual Result:
In the experiment page of the Spectrographic analysis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i11](https://cloud.githubusercontent.com/assets/13479177/26519887/bfb64b5a-42e5-11e7-953e-8c1f2caca362.png)

**Comment by sravanthimodepu** [comment]
Simulation is existed in the page and runs with Java but loads slowly. Hence differing the issue.

**Comment by BSravanthi** [comment]
Though the experiment runs with the java, the basic experiment should be displayed whether the experiment runs or not. Now the experiment is displaying on even small screen, hence closing the issue #36
