### ISSUE TITLE
QA_speech-signal-processing_Cepstral analysis of speech_Tutorial_missed-content-and-images

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#37]
Defect Description:
In the Tutorial page of the Cepstral analysis of speech experiment in Speech Signal Processing Lab, found that content and images are missed while porting.

Actual Result:
In the Tutorial page of the Cepstral analysis of speech experiment in Speech Signal Processing Lab, found that content and images are missed while porting.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i12](https://cloud.githubusercontent.com/assets/13479177/26519990/d447c826-42e7-11e7-932d-59ed61076b49.png)

**Comment by sravanthimodepu** [comment]
Added the images which are missed while porting. Hence resolved the issues.

**Comment by BSravanthi** [comment]
Still the images are not found. Hence reopening the issue.

**Comment by sravanthimodepu** [comment]
Added the Images. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Closed #37
