### ISSUE TITLE
QA_speech-signal-processing_Cepstral analysis of speech_Experiment_unwanted-text

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#38]
Defect Description:
In the experiment page of the Cepstral analysis of speech experiment in Speech Signal Processing Lab, after the small screen of the experiment, some text is given which may be unwanted.

Actual Result:
In the experiment page of the Cepstral analysis of speech experiment in Speech Signal Processing Lab, after the small screen of the experiment, some text is given which may be unwanted.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i13](https://cloud.githubusercontent.com/assets/13479177/26520124/16ffee26-42ea-11e7-8232-eae3cded5dff.png)

**Comment by sravanthimodepu** [comment]
Removed the unwanted text from the experiment page. Hence the issue is resolved.

**Comment by BSravanthi** [comment]
Closed #38
