### ISSUE TITLE
QA_speech-signal-processing_Cepstral analysis of speech_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#39]
Defect Description:
In the experiment page of the Cepstral analysis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Actual Result:
In the experiment page of the Cepstral analysis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i14](https://cloud.githubusercontent.com/assets/13479177/26520135/5fc1fa28-42ea-11e7-9cab-611961dd576c.png)

**Comment by sravanthimodepu** [comment]
Simulation is existed in the page and runs with Java but loads slowly. Hence differing the issue.
