### ISSUE TITLE
QA_Defect_Speech production mechanism_07

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#4]
Defect Description:
In the experiment page of the "Manual speech signal-to-symbol", in part 1 after selecting an utterance without clicking on the play button the record button is enabled where the record button should be disabled.

Actual Result :
In the experiment page of the "Speech production mechanism", without clicking on the play button the record button is enabled

Environment :
OS: Windows 7, Linux
Browsers: Firefox,Chrome
Bandwidth : 100mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Severity : S2

**Comment by khushpreet-kaur** [comment]
Which `play` button? 

I could not find any `Play` button in `Speech Production Mechanism Experiment` page of `Speech Signal Processing Lab`.

Are you talking about `Go` and `Reset` buttons? And this experiment has two parts. So for which part you are talking about?

Can you please describe it in more detail?

**Comment by khushpreet-kaur** [comment]
Can you please tell what does `07` mean in heading i.e `QA_Defect_Speech production mechanism_07`?

**Comment by kolliSuman** [comment]
"QA_Defect_Speech production mechanism_07" here 07 is the number of the defects raised by the QA team

**Comment by BSravanthi** [comment]
Issue is closed.
