### ISSUE TITLE
QA_speech-signal-processing_Linear prediction analysis of speech_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#40]
Defect Description:
In the experiment page of the Linear prediction analysis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Actual Result:
In the experiment page of the Linear prediction analysis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i15](https://cloud.githubusercontent.com/assets/13479177/26520494/34880954-42f1-11e7-8760-e135674af1c8.png)

**Comment by sravanthimodepu** [comment]
Simulation is existed in the page and runs with Java but loads slowly. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #40
