### ISSUE TITLE
QA_speech-signal-processing_Linear prediction analysis of speech_Assessment_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#41]
Defect Description:
In the Assessment page of the Linear prediction analysis of speech experiment in Speech Signal Processing Lab, Found spelling mistakes.

Actual Result:
In the Assessment page of the Linear prediction analysis of speech experiment in Speech Signal Processing Lab, Found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i16](https://cloud.githubusercontent.com/assets/13479177/26520519/e53bddc0-42f1-11e7-8a97-0dc67f583f70.png)

**Comment by sravanthimodepu** [comment]
All the spellings are correct. Hence differing the issue.

**Comment by BSravanthi** [comment]
Yet to be fixed the issue, hence re-opening.

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistake. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #41
