### ISSUE TITLE
QA_speech-signal-processing_Formant synthesis_Tutorial_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#42]
Defect Description:
In the Tutorial page of the Formant synthesis experiment in Speech Signal Processing Lab, Found spelling mistakes.

Actual Result:
In the Tutorial page of the Formant synthesis experiment in Speech Signal Processing Lab, Found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i17](https://cloud.githubusercontent.com/assets/13479177/26520705/6bc9b9ae-42f5-11e7-82b8-faace7bab29f.png)

**Comment by sravanthimodepu** [comment]
All the spellings are correct in the tutorial page. Hence differing the issue.

**Comment by BSravanthi** [comment]
Yet to fix the spelling mistake. Hence re opening the issue.

**Comment by sravanthimodepu** [comment]
Fixed all the spelling mistakes. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #42
