### ISSUE TITLE
QA_speech-signal-processing_Formant synthesis_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#43]
Defect Description:
In the experiment page of the Formant synthesis experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Actual Result:
In the experiment page of the Formant synthesis experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i18](https://cloud.githubusercontent.com/assets/13479177/26520728/b6510342-42f5-11e7-852b-c8cc2c2056f3.png)

**Comment by sravanthimodepu** [comment]
Simulation is ported properly, as it runs with java loads slowly. Hence differing the issue.

**Comment by BSravanthi** [comment]
Closed #43
