### ISSUE TITLE
QA_speech-signal-processing_Analysis-by-synthesis of speech_Objective_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#44]
Defect Description:
In the Objective page of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, Found spelling mistakes.

Actual Result:
In the Objective page of the Formant synthesis experiment in Speech Signal Processing Lab, Found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i19](https://cloud.githubusercontent.com/assets/13479177/26520776/786bd088-42f6-11e7-903c-a4622b0b52a1.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #44
