### ISSUE TITLE
QA_speech-signal-processing_Analysis-by-synthesis of speech_procedure_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#45]
Defect Description:
In the Procedure page of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, Found spelling mistakes.

Actual Result:
In the Procedure page of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, Found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i20](https://cloud.githubusercontent.com/assets/13479177/26520812/8089ef06-42f7-11e7-8141-d381a1a08392.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes. Hence the issue is resolved.

**Comment by BSravanthi** [comment]
Closed #45
