### ISSUE TITLE
QA_speech-signal-processing_Analysis-by-synthesis of speech_Experiment_disabled-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#46]
Defect Description:
In the experiment page of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Actual Result:
In the experiment page of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, the experiment is disabled in small screen and displaying in full screen.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i21](https://cloud.githubusercontent.com/assets/13479177/26520840/2c0aaee2-42f8-11e7-8f0f-f4992c9d0c67.png)

**Comment by sravanthimodepu** [comment]
Simulation is existed in the page and runs with Java but loads slowly. Hence differing the issue.

**Comment by BSravanthi** [comment]
Reopening the issue as it is not differed issue and an issue related to UI

**Comment by sravanthimodepu** [comment]
As there is no simulation in the vlab.co.in nad vlabs.ac.in, hiding the simulation from the list. Hence the issue is on hold..
