### ISSUE TITLE
QA_speech-signal-processing_Analysis-by-synthesis of speech_Experiment_experiment-is-not-provided

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#47]
Defect Description:
In the experiment page of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, on click full screen the page is redirecting to the same experiment of vlabs page. In the vlabs page no experiment is provided. 

Actual Result:
In the experiment page of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, on click full screen the page is redirecting to the same experiment of vlabs page. In the vlabs page no experiment is provided. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i21](https://cloud.githubusercontent.com/assets/13479177/26520860/9732869a-42f8-11e7-85af-e034190f1692.png)

**Comment by sravanthimodepu** [comment]
Simulation is existed in the page and runs with Java but loads slowly. Hence differing the issue.

**Comment by BSravanthi** [comment]
The issue is re opening as there is no experiment provided even in the vlabs page also.

**Comment by sravanthimodepu** [comment]
As there is no experiment in the vlab.co.in and vlabs.ac.in, hiding the experiment from the experiment list.
