### ISSUE TITLE
QA_speech-signal-processing_Analysis-by-synthesis of speech_Feedback_section-repeated-twice

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#48]
Defect Description:
The Feedback section of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, is repeated twice.

Actual Result:
The Feedback section of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, is repeated twice. 
 
Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i22](https://cloud.githubusercontent.com/assets/13479177/26520933/2a9ed9b4-42fa-11e7-8bf9-327fee2f4ab4.png)

**Comment by sravanthimodepu** [comment]
Removed the extra feedback section. Hence the issue is resolved.

**Comment by BSravanthi** [comment]
Closed #48
