### ISSUE TITLE
QA_speech-signal-processing_Analysis-by-synthesis of speech_Feedback_feedback-unit-is-not-included

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#49]
Defect Description:
In the Feedback section of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, On click on both the feedback sections: 
Though both the sections are included with feedback subsection, No feedback unit is provided. 

Actual Result:
In the Feedback section of the Analysis-by-synthesis of speech experiment in Speech Signal Processing Lab, On click on both the feedback sections: 
Though both the sections are included with feedback subsection, No feedback unit is provided. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i23](https://cloud.githubusercontent.com/assets/13479177/26520952/a96bea98-42fa-11e7-8383-f6a38e283e7b.png)

**Comment by sravanthimodepu** [comment]
Updated the Feedback. Hence issue is resolved.

**Comment by BSravanthi** [comment]
Closed #49
