### ISSUE TITLE
QA_iiith_Speech Signal Processing

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#5]
Defect Description :
In Speech Signal Processing Lab,when we click on the lab it is redirecting to the lab page but the page is not completely reloading and the feature links are missing in the page ,where the page should be completely reloaded.

Actual Result :
In Speech Signal Processing Lab,when we click on the lab it is redirecting to the lab page but the page is not completely reloading and the feature links are missing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

![ssp](https://cloud.githubusercontent.com/assets/14869397/13315119/e3debd98-dbce-11e5-8828-fa854fdacb5a.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed the issue.
