### ISSUE TITLE
QA_speech-signal-processing_all-experiments_full-screen-button-navigating-to-vlabs-page

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#50]
Defect Description:
In all the Experiment sections of the Speech Signal Processing lab, on click on experiment, the link is navigating to vlabs page of corresponding experiments. Instead the experiment should be performed in the open edx platform itself. Seems the experiment sections needs to be ported using iframe tool. 

Actual Result:
In all the Experiment sections of the Speech Signal Processing lab, on click on experiment, the link is navigating to vlabs page of corresponding experiments. Instead the experiment should be performed in the open edx platform itself. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:

**Comment by sravanthimodepu** [comment]
As the pages are written in php, only the simulation cannot be separated. from the page. Hence remained the same in the simulation page.

**Comment by BSravanthi** [comment]
Checked with development team and keeping on hold
