### ISSUE TITLE
QA_speech-signal-processing_Cepstral analysis of speech_Experiment_could-not-find-small-screen-while-retesting

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#51]
Defect Description:
While testing issue #38 found that in the experiment page of the Cepstral analysis of speech experiment in Speech Signal Processing Lab, the small screen is disabled. Where as earlier though the experiment was not appearing in small screen the screen it self was present. 

Actual Result:
While testing issue #38 found that in the experiment page of the Cepstral analysis of speech experiment in Speech Signal Processing Lab, the small screen is disabled. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Refer to issue #38 and the following screen shot
![qa_oe_ssp_i24](https://user-images.githubusercontent.com/13479177/27318734-b28ff97a-55ab-11e7-9bdf-0c8b89193941.png)

**Comment by sravanthimodepu** [comment]
Experiment link is updated in the small screen. Hence reolsved the issue.

**Comment by BSravanthi** [comment]
The Small screen is not responsive/consistent. When I zoom in the content in the small screen is exceeding the small screen. Hence re opening the issue.
