### ISSUE TITLE
QA_speech-signal-processing_Analysis-by-synthesis of speech_Feedback_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/speech-signal-processing-iiith#52]
Defect Description:
While testing issue #49 found that the link provided while fixing the issue is unassigned. Need to assign feed back link instead of pure text.

Actual Result:
While testing issue #49 found that the link provided while fixing the issue is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Refer to issue #49 and the following screen shot:

![qa_oe_ssp_i25](https://user-images.githubusercontent.com/13479177/27318998-ec8e236c-55ac-11e7-8b19-8bce1ff8da91.png)

**Comment by sravanthimodepu** [comment]
Assigned the appropriate link to the feedback. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #52
