### ISSUE TITLE
QA_speech-signal-processing_Cepstral analysis of speech_Experiment_Footer-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#54]
Defect Description:
While testing issue #51 found that in the footer is displaying partially in the small screen of the "Cepstral analysis of speech" experiment in Speech Signal Processing Lab. 

Actual Result:
While testing issue #51 found that in the footer is displaying partially in the small screen of the "Cepstral analysis of speech" experiment in Speech Signal Processing Lab. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Refer to issue #51 and the following screen shot
![qa_oe_ssp_i27](https://user-images.githubusercontent.com/13479177/27478511-8dce397e-582d-11e7-8865-b50cc52f26a2.png)

**Comment by sravanthimodepu** [comment]
This issue will be fixed by the system's team. Hence keeping the issue onhold.
