### ISSUE TITLE
QA_speech-signal-processing_Formant synthesis_Experiment_Footer-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#55]
Defect Description:
While testing issue #43 found that the footer is displaying partially in the small screen of the "Formant synthesis" experiment in Speech Signal Processing Lab. Where as the whole page should be displayed to maintain the consistency.

Actual Result:
While testing issue #43 found that the footer is displaying partially in the small screen of the "Formant synthesis" experiment in Speech Signal Processing Lab. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Refer to issue #43 and the following screen shot
![qa_oe_ssp_i28](https://user-images.githubusercontent.com/13479177/27571390-015173aa-5b23-11e7-9154-5a40255e746c.png)

**Comment by sravanthimodepu** [comment]
This issue will be fixed by the system's team. Hence keeping the issue onhold.
