### ISSUE TITLE
QA_speech-signal-processing_Linear prediction analysis of speech_Experiment_scroll-bar-needs-to-be-given-for-full-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#57]
Defect Description:
While testing issue #40, in the full screen of the "Linear prediction analysis of speech" experiment found that there is no scroll bar is provided in the full screen in order to go through the entire page. To view the whole page we need to zoom out which is effecting the visibility of the page.

Actual Result:
While testing issue #40, in the full screen of the "Linear prediction analysis of speech" experiment found that there is no scroll bar is provided in the full screen in order to go through the entire page. To view the whole page we need to zoom out which is effecting the visibility of the page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i29](https://user-images.githubusercontent.com/13479177/27571577-58004da6-5b24-11e7-9f52-848e999ec2d7.png)

**Comment by sravanthimodepu** [comment]
This issue will be fixed by the system's team. Hence keeping the issue onhold.
