### ISSUE TITLE
QA_speech-signal-processing_Spectrographic analysis of speech_Experiment_Footer-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#59]
Defect Description:
While testing issue #36 found that the footer is displaying partially in the small screen of the "Spectrographic analysis of speech" experiment in Speech Signal Processing Lab. Where as the whole page should be displayed to maintain the consistency.

Actual Result:
While testing issue #36 found that the footer is displaying partially in the small screen of the "Spectrographic analysis of speech" experiment in Speech Signal Processing Lab. Where as the whole page should be displayed to maintain the consistency.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Refer to issue #36 and the following screen shot
![qa_oe_ssp_i30](https://user-images.githubusercontent.com/13479177/27571925-9097462c-5b26-11e7-832a-fffcbaceed4e.png)

**Comment by sravanthimodepu** [comment]
This issue will be fixed by the system's team. Hence keeping the issue on hold.
