### ISSUE TITLE
QA_Analysis-by-synthesis of speech_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#6]
Defect Description:
In the experiment page of the "Analysis-by-synthesis of speech", without clicking on the play button the record button is enabled where the record button should be disabled.

Actual Result :
In the experiment page of the "Analysis-by-synthesis of speech", without clicking on the play button the record button is enabled

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/peech-signal-processing-iiith/blob/master/test-cases/integration_test-cases/Analysis-by-synthesis%20of%20speech/Analysis-by-synthesis%20of%20speech_07_Experiment_p1.org

Attachment:
![analysis](https://cloud.githubusercontent.com/assets/14869397/14705049/5d9187c4-07d5-11e6-8794-339babcee036.png)

**Comment by BSravanthi** [comment]
Closed the issue.
