### ISSUE TITLE
QA_speech-signal-processing_Nature of speech signal_Experiment_Footer-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#62]
Defect Description:
While testing issue #31 found that the footer is displaying partially in the small screen of the "Nature of speech signal" experiment in Speech Signal Processing Lab. Where as the whole page should be displayed to maintain the consistency.

Actual Result:
While testing issue #31 found that the footer is displaying partially in the small screen of the "Nature of speech signal" experiment in Speech Signal Processing Lab. Where as the whole page should be displayed to maintain the consistency.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Refer to issue #31 and the following screen shot
![qa_oe_ssp_i32](https://user-images.githubusercontent.com/13479177/27572415-81451ed0-5b29-11e7-84b2-a2e79d803e26.png)

**Comment by sravanthimodepu** [comment]
This issue will be fixed by the system's team. Hence keeping the issue on hold.
