### ISSUE TITLE
QA_speech-signal-processing_Speech production mechanism_Experiment_Footer-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#63]
Defect Description:
While testing issue #30 found that the footer is displaying partially in the small screen of the "Speech production mechanism" experiment in Speech Signal Processing Lab. Where as the whole page should be displayed to maintain the consistency.

Actual Result:
While testing issue #30 found that the footer is displaying partially in the small screen of the "Speech production mechanism" experiment in Speech Signal Processing Lab. Where as the whole page should be displayed to maintain the consistency.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Refer to issue #30 and the following screen shot
![qa_oe_ssp_i34](https://user-images.githubusercontent.com/13479177/27572531-305f49cc-5b2a-11e7-972e-eeb534f85cdc.png)

**Comment by sravanthimodepu** [comment]
This issue will be fixed by the system's team. Hence keeping this issue on hold.
