### ISSUE TITLE
QA_speech-signal-processing_Manual speech signal-to-symbol transformation_Experiment_Footer-in-small-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#65]
Defect Description:
While testing issue #29 found that the UI of the footer is inconsistent in the small screen of the "Manual speech signal-to-symbol transformation" experiment in Speech Signal Processing Lab. 

Actual Result:
While testing issue #29 found that the UI of the footer is inconsistent in the small screen of the "Manual speech signal-to-symbol transformation" experiment in Speech Signal Processing Lab. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
Refer to issue #29 and the following screen shot
![qa_oe_ssp_i37](https://user-images.githubusercontent.com/13479177/27573663-9bcb6df2-5b30-11e7-9481-e7101ab8e767.png)

**Comment by sravanthimodepu** [comment]
This issue will be fixed by the system's team. Hence keeping the issue onhold
