### ISSUE TITLE
QA_speech-signal-processing_Manual speech signal-to-symbol transformation_Experiment_scroll-bar-needs-to-be-given-for-full-screen

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/speech-signal-processing-iiith#66]
Defect Description:
While testing issue #29, in the full screen of the "Manual speech signal-to-symbol transformation" experiment found that there is no scroll bar is provided in the full screen in order to go through the entire page. To view the whole page we need to zoom out, which is effecting the visibility of the page.

Actual Result:
While testing issue #29, in the full screen of the "Manual speech signal-to-symbol transformation" experiment found that there is no scroll bar is provided in the full screen in order to go through the entire page. To view the whole page we need to zoom out which is effecting the visibility of the page. Though zoomed out unable to view the complete page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_ssp_i38](https://user-images.githubusercontent.com/13479177/27573738-e29ef9c4-5b30-11e7-9437-1a8c127e26d1.png)

**Comment by sravanthimodepu** [comment]
This issue should by fixed by the system's team. Hence keeping the issue onhold.
