### ISSUE TITLE
QA_Linear prediction analysis of s_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#7]
Defect Description:
In the experiment page of the "Linear prediction analysis of speech", without clicking on the play button the record button is enabled where the record button should be disabeled.

Actual Result :
In the experiment page of the "Linear prediction analysis of speech", without clicking on the play button the record button is enabled

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/peech-signal-processing-iiith/blob/master/test-cases/integration_test-cases/Linear%20prediction%20analysis%20of%20s/Linear%20prediction%20analysis%20of%20s_07_Experiment_p1.org

Attachment:
![linear](https://cloud.githubusercontent.com/assets/14869397/14705101/96e19316-07d5-11e6-8f11-846d9d9e94b3.png)

**Comment by BSravanthi** [comment]
Closed the issue.
