### ISSUE TITLE
QA_Cepstral analysis of speech_1.0_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#8]
Defect Description:
In the experiment page of the "Cepstral analysis of speech", without clicking on the play button the record button is enabled where the record button should be disabled.

Actual Result :
In the experiment page of the "Cepstral analysis of speech", without clicking on the play button the record button is enabled

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/peech-signal-processing-iiith/blob/master/test-cases/integration_test-cases/Cepstral%20analysis%20of%20speech_1.0/Cepstral%20analysis%20of%20speech_1.0_07_Experiment_p1.org

Attachment:
![ceptral](https://cloud.githubusercontent.com/assets/14869397/14705195/f99308a0-07d5-11e6-8c4b-1ad2a002f7fc.png)

**Comment by BSravanthi** [comment]
Closed the issue.
