### ISSUE TITLE
QA_Spectrographic analysis of spee_Experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/speech-signal-processing-iiith#9]
Defect Description:
In the experiment page of the "Spectrographic analysis of speech", without clicking on the play button the record button is enabled where the record button should be disabled.

Actual Result :
In the experiment page of the "Spectrographic analysis of speech", without clicking on the play button the record button is enabled

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/peech-signal-processing-iiith/blob/master/test-cases/integration_test-cases/Spectrographic%20analysis%20of%20spee/Spectrographic%20analysis%20of%20spee_07_Experiment_p1.org

Attachment:
![spectral](https://cloud.githubusercontent.com/assets/14869397/14705277/4f26da1c-07d6-11e6-8e4b-b0d1c0aae758.png)

**Comment by BSravanthi** [comment]
Closing the issue as the issue is differed.
